DBT:
  target: dev
  outputs:
    dev:
      type: spark
      method: session
      schema: gold     # This is the database (can be just a name used by Spark)
      threads: 4
      connect_retries: 1