name: gold_layer
version: "1.0"
config-version: 2

profile: spark_profile

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  gold_layer:
    marts:
      +materialized: parquet
    staging:
      +materialized: view
