DBT:
  target: dev
  outputs:
    dev:
      type: spark
      method: session
      schema: default
      file_format: parquet
      location_root: "hdfs://hadoop-namenode:8020/user/silver"
      threads: 4
